window.NTUTHUKO_INTAKE_SERVICES = [
  { category: "Compliance & Business Enablement", slug: "compliance-discovery", name: "Compliance Discovery", docs: "Existing registrations, licences, policies and compliance records" },
  { category: "Compliance & Business Enablement", slug: "tender-readiness", name: "Tender Readiness", docs: "CSD report, tax status, B-BBEE record, company profile and tender documents" },
  { category: "Compliance & Business Enablement", slug: "funding-readiness", name: "Funding Readiness", docs: "Business plan, financial records, registration documents and funding brief" },
  { category: "Compliance & Business Enablement", slug: "ohs-compliance", name: "Occupational Health & Safety Compliance", docs: "Existing OHS file, incident records, premises details and staff information" },
  { category: "Compliance & Business Enablement", slug: "fire-safety-readiness", name: "Fire & Insurer Readiness", docs: "Premises photos, insurer requests, fire equipment records and previous reports" },
  { category: "Compliance & Business Enablement", slug: "popia-paia-support", name: "POPIA & PAIA Support", docs: "Current policies, data-handling processes and organisation details" },
  { category: "Compliance & Business Enablement", slug: "bbbee-support", name: "B-BBEE Support", docs: "Registration records, ownership details, turnover information and existing affidavit/certificate" },
  { category: "Compliance & Business Enablement", slug: "csd-registration", name: "CSD Registration", docs: "CIPC documents, tax details, bank confirmation and director information" },
  { category: "Tax Services", slug: "income-tax-registration", name: "Income Tax Registration", docs: "Identity, CIPC and SARS-related records" },
  { category: "Tax Services", slug: "vat-registration", name: "VAT Registration", docs: "Turnover evidence, invoices, bank statements and company records" },
  { category: "Tax Services", slug: "paye-registration", name: "PAYE Registration", docs: "Employee and payroll information, CIPC and SARS records" },
  { category: "Tax Services", slug: "uif-registration", name: "UIF Registration", docs: "Employer, employee and company information" },
  { category: "Tax Services", slug: "sdl-registration", name: "SDL Registration", docs: "Payroll estimates and employer records" },
  { category: "Tax Services", slug: "tax-compliance-status", name: "Tax Compliance Status & PIN", docs: "SARS profile details, notices, statements and outstanding-return information" },
  { category: "Tax Services", slug: "outstanding-tax-returns", name: "Outstanding Tax Returns", docs: "Relevant financial records, prior returns and SARS correspondence" },
  { category: "Tax Services", slug: "tax-debt-penalties", name: "Tax Debt & Penalty Support", docs: "SARS statements, penalty notices, income and affordability information" },
  { category: "Tax Services", slug: "efiling-profile-support", name: "SARS eFiling Profile Support", docs: "Identity, contact information and available SARS correspondence" },
  { category: "Tax Services", slug: "bookkeeping-support", name: "Bookkeeping Support", docs: "Bank statements, invoices, receipts and existing accounting records" },
  { category: "CIPC Services", slug: "company-registration", name: "CIPC Company Registration", docs: "Director identity documents, contact details and proposed company names" },
  { category: "CIPC Services", slug: "name-reservation", name: "Company Name Reservation", docs: "Proposed names and applicant details" },
  { category: "CIPC Services", slug: "company-amendments", name: "Company Amendments", docs: "Current CIPC documents and requested changes" },
  { category: "CIPC Services", slug: "annual-returns", name: "CIPC Annual Returns", docs: "Company registration number and turnover information" },
  { category: "CIPC Services", slug: "beneficial-ownership", name: "Beneficial Ownership Filing", docs: "Ownership structure, shareholder and director records" },
  { category: "CIPC Services", slug: "company-reinstatement", name: "Company Reinstatement", docs: "Deregistration notice, CIPC documents and supporting activity records" },
  { category: "CIPC Services", slug: "director-changes", name: "Director Changes", docs: "Current and incoming director details and resolutions" },
  { category: "CIPC Services", slug: "npo-registration", name: "NPO Registration & Support", docs: "Founding member details, constitution information and organisation purpose" },
  { category: "Web & Digital Services", slug: "website-development", name: "Website Development", docs: "Logo, business profile, services, contact information and preferred imagery" },
  { category: "Web & Digital Services", slug: "google-business-profile", name: "Google Business Profile Setup", docs: "Business details, location, hours, logo, photos and public contact information" },
  { category: "Web & Digital Services", slug: "professional-email", name: "Professional Business Email", docs: "Domain details, desired email addresses and authorised contact information" },
  { category: "Web & Digital Services", slug: "domain-registration", name: "Domain Registration", docs: "Preferred domain names and registrant details" },
  { category: "Web & Digital Services", slug: "website-hosting", name: "Website Hosting & Maintenance", docs: "Current website, domain and hosting access information" },
  { category: "Web & Digital Services", slug: "seo-support", name: "SEO & Search Visibility", docs: "Website address, target services, locations and priority keywords" },
  { category: "Web & Digital Services", slug: "company-profile-design", name: "Company Profile Design", docs: "Logo, services, history, team details, credentials and project images" },
  { category: "Web & Digital Services", slug: "digital-branding", name: "Digital Branding Support", docs: "Existing logo files, brand references and business positioning" },
  { category: "Ntuthuko Connects", slug: "stick-to-business", name: "Stick To Business", docs: "Short business description and current goals" },
  { category: "Ntuthuko Connects", slug: "friday-coffee-club", name: "Friday Coffee Club", docs: "Business or professional profile and networking interests" },
  { category: "Ntuthuko Connects", slug: "basadi-in-business", name: "Basadi in Business", docs: "Business stage, goals and support needs" },
  { category: "Ntuthuko Connects", slug: "tender-masterclasses", name: "Tender Masterclasses", docs: "Business registration status, industry and tender-readiness goals" },
  { category: "Business Development", slug: "business-plan-writing", name: "Business Plan Writing", docs: "Business concept, market, operations, financial assumptions and funding purpose" },
  { category: "Business Development", slug: "business-consultation", name: "Business Consultation", docs: "Current challenge, goals and relevant business documents" },
  { category: "Business Development", slug: "customer-success-support", name: "Ongoing Customer Success Support", docs: "Current services, open issues and upcoming priorities" }
];
